plugins {
	id 'net.fabricmc.fabric-loom'
}

base {
	archivesName = "Leafs-fabric-${minecraftMajor}"
}

configurations {
	mods
	compileOnly.extendsFrom(mods)
	localRuntime.extendsFrom(mods)
	testImplementation.extendsFrom(mods)
}

dependencies {
	minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${rootProject.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
	mods "maven.modrinth:scalablelux:${rootProject.scalablelux_fabric}"
	mods "fr.hardel:mapple-fabric-${minecraftMajor}:${rootProject.mapple_version}"

	testImplementation platform("org.junit:junit-bom:5.12.2")
	testImplementation "org.junit.jupiter:junit-jupiter"
	testImplementation "net.fabricmc:fabric-loader-junit:${rootProject.loader_version}"
	testImplementation rootProject.project(':common').sourceSets.test.output
	testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

loom {
	accessWidenerPath = project(':common').file('src/main/resources/leafs.accesswidener')

	runs {
		configureEach {
			vmArg "-ea"
			vmArg "-XX:+UseZGC"
		}

		client {
			vmArg "-Xmx8G"
		}

		server {
			vmArg "-Xms8G"
			vmArg "-Xmx8G"
			vmArg "-XX:+AlwaysPreTouch"
		}
	}
}

fabricApi {
	configureTests {
		createSourceSet = true
		modId = "leafs-gametest"
		eula = true
	}
}

tasks.named('compileJava') {
	source(project(':common').sourceSets.main.allJava)
}

tasks.named('sourcesJar') {
	from(project(':common').sourceSets.main.allSource)
}

test {
	useJUnitPlatform()
}

processResources {
	from(project(':common').sourceSets.main.resources)
	def metadata = [
		version: project.version,
		minecraft: rootProject.minecraft_version,
		scalablelux: ">=${rootProject.scalablelux_fabric.tokenize('+')[0]} <${rootProject.scalablelux_below}"
	]
	inputs.properties metadata

	filesMatching('fabric.mod.json') {
		expand metadata
	}
}

publishing {
	publications {
		create('mavenJava', MavenPublication) {
			artifactId = "leafs-fabric-${minecraftMajor}"
			from components.java
		}
	}
}
